# Generated by Django 4.1.1 on 2022-09-27 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='address',
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='phonenumber',
            field=models.TextField(null=True),
        ),
    ]
